import type { TraitKey } from "@player-dna/player-matching";
import type { RoleFamily } from "./types";

export type Language = "zh" | "en";

export const roleLabelsZh: Record<RoleFamily, string> = {
  winger: "边锋",
  fullback: "边后卫",
  defender: "后卫",
  forward: "前锋",
  midfielder: "中场",
  goalkeeper: "门将",
};

export const roleLabelsEn: Record<RoleFamily, string> = {
  winger: "Winger",
  fullback: "Fullback",
  defender: "Defender",
  forward: "Forward",
  midfielder: "Midfielder",
  goalkeeper: "Goalkeeper",
};

export const traitLabelsZh: Record<TraitKey, string> = {
  pace: "速度",
  acceleration: "爆发",
  dribbling: "盘带",
  oneVsOne: "一对一",
  cutInside: "内切",
  goOutside: "走外线",
  shooting: "射门",
  finishing: "终结",
  crossing: "传中",
  passing: "传球",
  creativity: "创造力",
  offBall: "无球跑动",
  defensiveWorkRate: "防守投入",
  pressing: "压迫",
  tackling: "抢断",
  interceptions: "拦截",
  marking: "盯防",
  physicality: "对抗",
  holdUpPlay: "背身支点",
  riskTaking: "冒险度",
  tempoControl: "节奏控制",
  transitionThreat: "反击威胁",
  weakFoot: "弱脚",
  aerialAbility: "制空",
  ballRetention: "护球稳定性",
  longPassing: "长传",
  shortCombination: "小范围配合",
  finalThirdDecision: "前场决策",
  shotStopping: "扑救",
  reflexes: "反应",
  handling: "手型稳定性",
  keeperDistribution: "门将出球",
  sweeperKeeping: "清道夫门将",
};

export const traitLabelsEn: Record<TraitKey, string> = {
  pace: "Pace",
  acceleration: "Acceleration",
  dribbling: "Dribbling",
  oneVsOne: "1v1",
  cutInside: "Cut Inside",
  goOutside: "Go Outside",
  shooting: "Shooting",
  finishing: "Finishing",
  crossing: "Crossing",
  passing: "Passing",
  creativity: "Creativity",
  offBall: "Off Ball",
  defensiveWorkRate: "Defensive Work Rate",
  pressing: "Pressing",
  tackling: "Tackling",
  interceptions: "Interceptions",
  marking: "Marking",
  physicality: "Physicality",
  holdUpPlay: "Hold-up Play",
  riskTaking: "Risk Taking",
  tempoControl: "Tempo Control",
  transitionThreat: "Transition Threat",
  weakFoot: "Weak Foot",
  aerialAbility: "Aerial Ability",
  ballRetention: "Ball Retention",
  longPassing: "Long Passing",
  shortCombination: "Short Combination",
  finalThirdDecision: "Final-third Decision",
  shotStopping: "Shot Stopping",
  reflexes: "Reflexes",
  handling: "Handling",
  keeperDistribution: "Keeper Distribution",
  sweeperKeeping: "Sweeper Keeping",
};

export const strengthCopyZh: Record<TraitKey, string> = {
  pace: "直线速度和冲刺威胁明显",
  acceleration: "第一步启动快，能迅速摆脱对手",
  dribbling: "持球推进和盘带能力突出",
  oneVsOne: "喜欢并擅长一对一解决问题",
  cutInside: "从边路内切制造威胁",
  goOutside: "能沿外线冲击并拉开宽度",
  shooting: "射门欲望和远射威胁强",
  finishing: "门前终结感觉好",
  crossing: "边路传中和倒三角能力突出",
  passing: "传球参与度和稳定性高",
  creativity: "能找到非常规的创造性选择",
  offBall: "无球跑位和前插意识强",
  defensiveWorkRate: "防守回追和责任感明显",
  pressing: "压迫积极，能给对手制造压力",
  tackling: "抢断时机和对抗处理出色",
  interceptions: "阅读线路和提前拦截能力强",
  marking: "盯人和跟跑意识稳定",
  physicality: "身体对抗和扛压能力强",
  holdUpPlay: "背身拿球和支点连接能力好",
  riskTaking: "敢做高收益的冒险选择",
  tempoControl: "能控制比赛节奏和进攻速度",
  transitionThreat: "反击和开放空间威胁大",
  weakFoot: "弱脚使用比较自然",
  aerialAbility: "头球和空中对抗能力强",
  ballRetention: "在压力下不容易丢球",
  longPassing: "长传转移和纵向输送能力好",
  shortCombination: "小范围连续配合能力突出",
  finalThirdDecision: "前场最后一脚选择清晰",
  shotStopping: "扑救能力突出",
  reflexes: "近距离反应速度快",
  handling: "接球和处理第二落点稳定",
  keeperDistribution: "门将出球参与度高",
  sweeperKeeping: "能主动保护身后空间",
};

export const developmentCopyZh: Record<TraitKey, string> = {
  pace: "提升长距离冲刺后的持续威胁",
  acceleration: "提升启动后的连续爆发",
  dribbling: "减少无谓盘带，提高持球效率",
  oneVsOne: "提升一对一后的最终处理",
  cutInside: "丰富内切后的传射选择",
  goOutside: "加强外线突破后的传中质量",
  shooting: "提升射门选择和稳定命中率",
  finishing: "提升门前处理的稳定性",
  crossing: "提升传中落点和时机",
  passing: "提升高压下传球稳定性",
  creativity: "平衡创造性和失误风险",
  offBall: "提高无球启动时机",
  defensiveWorkRate: "保持防守参与的连续性",
  pressing: "提升压迫路线和触发时机",
  tackling: "减少冒失上抢",
  interceptions: "提升提前观察和线路判断",
  marking: "提升盯人时的持续专注",
  physicality: "提升对抗后的技术动作衔接",
  holdUpPlay: "增强背身拿球后的连接质量",
  riskTaking: "控制高风险选择的时机",
  tempoControl: "提升不同节奏之间的切换",
  transitionThreat: "提升反击中的最后一脚",
  weakFoot: "继续提升弱脚传射信心",
  aerialAbility: "提升起跳时机和落点判断",
  ballRetention: "提升被夹击时的出球速度",
  longPassing: "提升长传精度和选择时机",
  shortCombination: "提升小范围配合后的前插意识",
  finalThirdDecision: "提升前场传射选择的一致性",
  shotStopping: "提升扑救后的二次控制",
  reflexes: "提升连续扑救能力",
  handling: "提升高球和湿滑球处理稳定性",
  keeperDistribution: "提升出球风险控制",
  sweeperKeeping: "提升出击判断和回撤时机",
};

export const strengthCopyEn: Record<TraitKey, string> = {
  pace: "Strong straight-line speed and sprint threat",
  acceleration: "Quick first step and sharp separation",
  dribbling: "Strong ball carrying and dribbling",
  oneVsOne: "Comfortable solving actions in 1v1s",
  cutInside: "Threatens by cutting inside from wide areas",
  goOutside: "Can attack the outside lane and stretch width",
  shooting: "Confident shot volume and shooting range",
  finishing: "Good penalty-box finishing instincts",
  crossing: "Strong wide delivery and cutback value",
  passing: "High passing involvement and stability",
  creativity: "Finds unexpected creative solutions",
  offBall: "Strong off-ball timing and movement",
  defensiveWorkRate: "Clear defensive effort and recovery responsibility",
  pressing: "Active pressure and defensive disruption",
  tackling: "Strong timing when engaging the ball carrier",
  interceptions: "Reads passing lanes early",
  marking: "Reliable tracking and direct opponent control",
  physicality: "Strong contact balance and duel profile",
  holdUpPlay: "Good back-to-goal receiving and linking",
  riskTaking: "Willing to attempt high-upside actions",
  tempoControl: "Can manage rhythm and game speed",
  transitionThreat: "Dangerous in open space and transitions",
  weakFoot: "Comfortable using the weaker foot",
  aerialAbility: "Strong aerial duel and heading profile",
  ballRetention: "Keeps possession under pressure",
  longPassing: "Good range when switching or progressing play",
  shortCombination: "Strong quick combination play",
  finalThirdDecision: "Clear final-third shot/pass/carry choices",
  shotStopping: "Strong shot-stopping profile",
  reflexes: "Quick reactions at close range",
  handling: "Secure catching and rebound control",
  keeperDistribution: "Useful buildup involvement as a goalkeeper",
  sweeperKeeping: "Can protect space behind the defensive line",
};

export const developmentCopyEn: Record<TraitKey, string> = {
  pace: "Improve repeat sprint threat over longer sequences",
  acceleration: "Improve second actions after the first burst",
  dribbling: "Reduce low-value carries and improve efficiency",
  oneVsOne: "Improve end product after beating a defender",
  cutInside: "Add more variety after cutting inside",
  goOutside: "Improve final delivery after outside bursts",
  shooting: "Improve shot selection and conversion quality",
  finishing: "Improve consistency around goal",
  crossing: "Improve delivery timing and target selection",
  passing: "Improve passing security under pressure",
  creativity: "Balance creativity with turnover risk",
  offBall: "Improve timing of off-ball starts",
  defensiveWorkRate: "Keep defensive effort more consistent",
  pressing: "Improve pressing angles and triggers",
  tackling: "Avoid overcommitting in defensive duels",
  interceptions: "Improve scanning and lane anticipation",
  marking: "Improve concentration when tracking runners",
  physicality: "Improve technical actions after contact",
  holdUpPlay: "Improve link play after receiving back to goal",
  riskTaking: "Control when to take high-risk options",
  tempoControl: "Improve switching between speeds",
  transitionThreat: "Improve final actions in transition",
  weakFoot: "Build more weak-foot passing and shooting confidence",
  aerialAbility: "Improve timing and reading of aerial balls",
  ballRetention: "Improve release speed when crowded",
  longPassing: "Improve long-pass timing and accuracy",
  shortCombination: "Improve forward movement after combinations",
  finalThirdDecision: "Improve consistency of final-third choices",
  shotStopping: "Improve second-ball control after saves",
  reflexes: "Improve repeat-save sequences",
  handling: "Improve handling under difficult conditions",
  keeperDistribution: "Improve distribution risk control",
  sweeperKeeping: "Improve timing of sweeper actions",
};

export function getRoleLabels(language: Language): Record<RoleFamily, string> {
  return language === "zh" ? roleLabelsZh : roleLabelsEn;
}

export function getTraitLabels(language: Language): Record<TraitKey, string> {
  return language === "zh" ? traitLabelsZh : traitLabelsEn;
}
